apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-deployment

spec:
  replicas: 3
  # selector:
  #   service: fe

  template:

    metadata:
      name: nodejs.iilunin.com
      labels:
        service: fe
    spec:
      containers:
      - name: nodejs-hz-container
        image: iilunin/hazelcast-cluster-test:latest
        ports:
        - name: node-js
          containerPort: 3000
        env:
        - name: HZ_PORT
          value: "5701"
        - name: HZ_HOST
          value: hazelcast-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  ports:
  - port: 80
    targetPort: node-js
    protocol: TCP
  selector:
    service: fe
  type: LoadBalancer
---
...
