apiVersion: v1
kind: Pod
metadata:
  name: node-hz.iilunin.com
  labels:
    service: fe
spec:
  containers:
  - name: nodejs-hz-container
    image: iilunin/hazelcast-cluster-test:latest
    ports:
    - name: node-js
      containerPort: 3000
    env:
    - name: HZ_PORT
      value: "5701"
    - name: HZ_HOST
      value: hz
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  ports:
  - port: 80
    targetPort: node-js
    protocol: TCP
  selector:
    service: fe
  type: LoadBalancer
...
